import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "../lib/components/header/header";
import Background from "../lib/components/background/background";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <html style={{ height: "100%" }} lang="en">
        <body className={inter.className} style={{ height: "100%" }}>
          <Background />
          <Header />
          <div style={{ width: "70%", margin: "auto" }}>{children}</div>
        </body>
      </html>
    </>
  );
}
